# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='username',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
