# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_remove_upload_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
