# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_upload_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(default='description', max_length=300),
        ),
    ]
