# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_upload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='bhave', max_length=100),
        ),
    ]
