# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_remove_upload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='docFile',
            field=models.FileField(default=None, upload_to=b''),
        ),
    ]
