# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_upload_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-timestamp']},
        ),
    ]
