# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_auto_20170915_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='docFile',
            field=models.FileField(blank=True, default=None, upload_to=b''),
        ),
    ]
