# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_upload_user'),
        ('uploads', '0011_auto_20170915_1102'),
    ]

    operations = [
    ]
